//
// Created by Khaldoun Alhalabi on 10/28/2023.
//

#ifndef SMART_ALGORITHMS_STONETYPEENUM_H
#define SMART_ALGORITHMS_STONETYPEENUM_H

enum StoneType {
    REPEL,
    ATTRACT,
    STONE,
    GOAL,
    OBSTACLE,
    EMPTY,
    REPELANDGOAL,
    ATTRACTANDGOAL,
    STONEANDGOAL
};

#endif //SMART_ALGORITHMS_STONETYPEENUM_H
